SELECT  'ALTER TABLE ' || FK.TABLE_SCHEMA || '.' || FK.TABLE_NAME || ' DROP CONSTRAINT ' || RTRIM(C.CONSTRAINT_NAME) || ';'
-- SELECT FK.TABLE_NAME as fk_tbl, CU.COLUMN_NAME as cu_column ,  PK.TABLE_NAME as PK_tbl,  PT.COLUMN_NAME as pt_column, C.CONSTRAINT_NAME as constraint
--  SELECT  'ALTER TABLE ' || FK.TABLE_SCHEMA || '.' || FK.TABLE_NAME || ' ADD CONSTRAINT ' || RTRIM(C.CONSTRAINT_NAME) || 
-- ' FOREIGN KEY (' || PK.CONSTRAINT_NAME || ') REFERENCES ' || PK.TABLE_NAME
from INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
    ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
    ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
 INNER JOIN (
            SELECT i1.TABLE_NAME, i2.COLUMN_NAME
              FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
             INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2
                ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
            WHERE i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
           ) PT
    ON PT.TABLE_NAME = PK.TABLE_NAME
